### ISSUE TITLE
File is not completely encrypt

### ISSUE THREAD

**Issue by chinkung** [jasonhinkle/php-gpg#1]
Hello,

After I use your library to encrypt, the encryption process is ok but after tried to decrypt with GnuPG 1.4.10 I found this error

gpg: WARNING: message was not integrity protected
gpg: [don't know]: invalid packet (ctb=74)
gpg: no valid OpenPGP data found.

and the file is partial decrypted

The key I use is 4096 bits and text file size is around 210 KB and text file contains UTF-8 (Thai) characters

**Comment by DanielRuf** [comment]
If the encrypted fileis over 250KB large, then the issue occurs.

It still happens.

**Comment by DanielRuf** [comment]
Found this code from openpgp.js

It seems we use the old v3 header.
We should try to use the v3 code from openpgp.js and s3 if this works.

It seems we have to add 1, 2 or 4 depending on the value of len.

Maybe the v4 header does also work.

```
 /**
   * Writes a packet header version 4 with the given tag_type and length to a
   * string
   * 
   * @param {Integer} tag_type Tag type
   * @param {Integer} length Length of the payload
   * @return {String} String of the header
   */
  writeHeader: function(tag_type, length) {
    /* we're only generating v4 packet headers here */
    var result = "";
    result += String.fromCharCode(0xC0 | tag_type);
    result += this.writeSimpleLength(length);
    return result;
  },

  /**
   * Writes a packet header Version 3 with the given tag_type and length to a
   * string
   * 
   * @param {Integer} tag_type Tag type
   * @param {Integer} length Length of the payload
   * @return {String} String of the header
   */
  writeOldHeader: function(tag_type, length) {
    var result = "";
    if (length < 256) {
      result += String.fromCharCode(0x80 | (tag_type << 2));
      result += String.fromCharCode(length);
    } else if (length < 65536) {
      result += String.fromCharCode(0x80 | (tag_type << 2) | 1);
      result += util.writeNumber(length, 2);
    } else {
      result += String.fromCharCode(0x80 | (tag_type << 2) | 2);
      result += util.writeNumber(length, 4);
    }
    return result;
  },
```

**Comment by jasonhinkle** [comment]
I'm not really able to give this a thorough look that it deserves.  If it helps, the phpunit tests should run and that might be a great place to put in a test case for this?

**Comment by DanielRuf** [comment]
Right, I will prepare a working commit when I find the time this week and let you know.

**Comment by DanielRuf** [comment]
I got some working code faster than I thought =) Please test and verify if it works.

At the moment we use the version 3 signature packet format (and so the v3 header).
Version 4 would need a big rewrite of many functions.

Reference:
https://tools.ietf.org/html/rfc4880#section-5.2.2 (v3)
https://tools.ietf.org/html/rfc4880#section-5.2.3 (v4)
