### ISSUE TITLE
proposed features

### ISSUE THREAD

**Issue by DanielRuf** [jasonhinkle/php-gpg#12]
In the readme these features are mentioned, which are missing:
- [ ] signing (needs private key)
- [ ] decryption (needs private key)
- [ ] signature verification (needs public key)
- [ ] key generation
- [x] MDC packet
- [ ] integrity check (needs private key)

Are there more things, which we need?
I think getting some contributors from https://github.com/openpgpjs/openpgpjs would be very helpful, as they support signing, decryption and much more.

Porting some of their functions would be the way I would go.

For decryption these are some of the functions used by OpenPGP.js:
decrypt (RSA, Elgamal)
readArmored (signed cleartext, armored text keys, armored text message object)
and all the used functions by these

https://github.com/openpgpjs/openpgpjs/blob/0958a9ec02565faf18e85f99de29a091180c6e46/dist/openpgp.js

**Comment by jasonhinkle** [comment]
I think that would be amazing. I suppose if I were going to add anything to the list it would be signature verification. That would pretty much cover all of the typical uses that I can think of.

**Comment by jasonhinkle** [comment]
Sorta related, I'm also going to try to get the phpunit tests running automatically on travis ci.

**Comment by DanielRuf** [comment]
Ok, added it to the list.

That would be great and very helpful for commits and pull requests.

**Comment by DanielRuf** [comment]
Signing and decryption need the private key, I am not sure if we should add these features and people store their private keys on servers. Personally I prefer libraries which just do the encryption and verification using public keys (one way). But this is just my opinion.

How do you see this?

**Comment by RaedsLab** [comment]
Getting users to handle privateKeys in variables will surely lead to some of those getting leaked. 
This can be implemented with a warning label over it.

**Comment by jasonhinkle** [comment]
It's almost a certainty that somebody would use the library in a way that would not be safe. But I don't think that's unique to this project. There's already PHP libraries to interface with the GPG binary. The only real difference is that this library is pure PHP. It is possible to write command-line PHP apps as well, though not a lot of people do it.

I'm not sure how much my opinion is worth since I probably lack the ability to implement either of those features anyway!

**Comment by jasonhinkle** [comment]
I just added key generation, i suppose if the plan is to eventually have a full-featured GPG library

**Comment by RaedsLab** [comment]
@jasonhinkle agreed , you can't always babysit people :+1:

**Comment by DanielRuf** [comment]
The structure of keys and signatures is described here: http://senderek.ie/research/security/key-experiments.html (very good and helpful article).

I got the two MPI for the modulus and exponent value from the public key now. But I am not sure howto calculate the right value of the modulus.

Any help is very welcome. But so far it seems I have the data from the signature which we need.

```
	private function gpg_session_verify($key_id, $key_type, $session_key, $public_key)
	{ 

		$mod = array();
		$exp = array();
	 
		$s = base64_decode($public_key);
		$l = floor((ord($s[0]) * 256 + ord($s[1]) + 7) / 8);
		$mod = mpi2b(substr($s, 0, $l + 2));
		if($key_type) {
			$grp = array();
			$y = array();
			$B = array();
			$C = array();

			$l2 = floor((ord($s[$l + 2]) * 256 + ord($s[$l + 3]) + 7) / 8) + 2;
			$grp = mpi2b(substr($s, $l + 2, $l2));
			$y = mpi2b(substr($s, $l + 2 + $l2));
			$exp[0] = $this->el[GPG_Utility::c_random() & 7];
			$B = bmodexp($grp, $exp, $mod);
			$C = bmodexp($y, $exp, $mod);
		} else {
			$exp = mpi2b(substr($s, $l + 2));
		}
		
		$val = new stdClass();
		

		$val->mod=$mod;
		$val->exp=$exp;
		if($key_type) {
		$val->grp=$grp;
		$val->Y=$Y;
		$val->B=$B;
		$val->C=$C;
		}
		
		return $val;
	}
	function get_verification_data($pk)
	{
		$key_id = $pk->GetKeyId();
		$key_type = $pk->GetKeyType();
		$public_key = $pk->GetPublicKey();

		$session_key = GPG_Utility::s_random($this->width, 0);
		$key_id = GPG_Utility::hex2bin($key_id);
		$val = $this->gpg_session_verify($key_id, $key_type, $session_key, $public_key);
		foreach($val->mod as $var){
			echo dechex($var);
		}
		echo "<br>";
		var_dump($val->exp);
	}
	
	
	
	$pub_key = new GPG_Public_Key(file_get_contents("publickey.asc"));
	$encrypted = $gpg->get_verification_data($pub_key);
```

SO question: http://stackoverflow.com/questions/33734918/how-do-i-get-modulus-and-exponent-from-public-key-for-signature-verification

Code so far for getting the data from the signature (just for testing and debugging at the moment):
```
$s =  base64_decode($signature);
$sa = str_split($s);
$subpacket_data=0;
$data='';
$subpacket_data_un=0;
for($i = 0; $i < strlen($s);) {
		ord($sa[$i++]);
// var_dump(ord($sa[$i++]));

if($i==3)$version=ord($sa[$i]);
if($i==4)$sig_type=ord($sa[$i]);
if($i==5)$key_alg=ord($sa[$i]);
if($i==6)$hash_alg=ord($sa[$i]);
if($i==7)$subpacket_data=ord($sa[$i])<<8;
if($i==8)$subpacket_data+=ord($sa[$i]);
if($i==8+$subpacket_data+1)$subpacket_data_un=ord($sa[$i])<<8;
if($i==8+$subpacket_data+2)$subpacket_data_un+=ord($sa[$i]);
if($i==8+$subpacket_data_un+1)$left_bit=ord($sa[$i])<<8;
if($i==8+$subpacket_data_un+2)$left_bit_2=ord($sa[$i]);
}

$subpacket_data_raw=ord($sa[9])<<40;
$subpacket_data_raw.=ord($sa[10])<<32;
$subpacket_data_raw.=ord($sa[11])<<24;
$subpacket_data_raw.=ord($sa[12])<<16;
$subpacket_data_raw.=ord($sa[13])<<8;
$subpacket_data_raw.=ord($sa[14]);
```

**Comment by DanielRuf** [comment]
I think I just missed the part to add zero3 to the begnning of the number if its length is smaller than 8.
http://stackoverflow.com/questions/14603205/how-to-convert-hex-string-into-a-bytes-array-and-a-bytes-array-in-the-hex-strin

**Comment by wyllys66** [comment]
The lack of MDC support causes some GPG clients to reject messages generated here.  Is this new version going to generate an MDC with the encrypted messages?

**Comment by DanielRuf** [comment]
@wyllys66 I don't know if it is already implemented.

Which software rejects the message?
Please open an new issue for this.

See here: https://github.com/jasonhinkle/php-gpg/issues/1#issuecomment-18958153

The warning is not critical. Decryption should still work.

**Comment by wyllys66** [comment]
The Mailvelope plugin for Chrome and Firefox rejects messages without an MDC, which apparently is what 1.4.7 generates. I haven't tested with 1.5.0 yet.  gpg just shows a warning when the MDC is missing.   It's easy to test to see if the MDC is generated, just use "gpg --list-packets" on the encrypted message to see if it is generating an encrypted data packet with the mdc:
```
:encrypted data packet:
	length: unknown
	mdc_method: 2
```

The messages generate by php-pgp do not have the MDC method:
```
:encrypted data packet:
	length: 546
```

See:  https://github.com/mailvelope/mailvelope/issues/341

**Comment by DanielRuf** [comment]
Please create a new issue for this here so we can properly discuss this.

So far MDC is optional and this issue is in mailvelope, not php-gpg.

**Comment by Maikuolan** [comment]
I've forked a copy of this repository and I'm watching this repository very closely. I don't yet know enough about its inner workings or about the code to contribute anything particularly useful, but, I'm slowly going over it all, in the hopes of learning it properly and finding ways to contribute.

If I can think of any suggestions, I'll post them here. In any case.. The project looks very interesting and seems very promising. :-)

As a side note.. I ran some encryption tests using php-gpg earlier today using some plain-text data in blocks of various sizes (the largest was 494,276 bytes), and everything (so far as encryption is concerned, at least; I haven't yet tested anything else with it) seems to be working correctly; I attempted to decrypt the encrypted data using GnuPG's Kleopatra, and it decrypted correctly, without any issues.

**Comment by jasonhinkle** [comment]
Thanks @Maikuolan !

**Comment by meitar** [comment]
I'd just like to +1 the request for signature verification. That seems like (relatively) low hanging fruit and it would be particularly useful for a project I am working on.

Many thanks for this tool, I can't promise to contribute code directly (yet) because I have too many other projects that need my attention, but I'll begin using this package in those projects and upstream whatever I can.

**Comment by DanielRuf** [comment]
This would be very helpful as we need more contributors who can help with this.
