### ISSUE TITLE
Undefined plaintext variable results in an undecryptable block

### ISSUE THREAD

**Issue by tobestool** [jasonhinkle/php-gpg#13]
Hi, I've been scratching my head trying to use this library with wp-pgp-email here: 

https://gist.github.com/timnashcouk/dd1ff318489f6bfd8743

Turns out that my headaches were caused by a typo in the variable being passed to the GPG::encrypt meaning that it was passed an undefined variable which resulted in what looked like a valid encrypted message, but neither Enigmail in Thunderbird or GNU Privacy Assistant would decrypt them. The same seems to happen if I pass in an empty string for encryption.

Is this the expected operation for a blank / undefined context, or does the fault lie with my decryption software? For reference, I've got gnupg 2.1.9 installed on a Windows 10 system.

Thanks in advance.

--Tobes

**Comment by DanielRuf** [comment]
I can not confirm this.

Encryption and decryption works with an empty input.
```
$plain_text_string = "";
$encrypted = $gpg->encrypt($pub_key,$plain_text_string);
```

I use GnuPG 2.0.29 and GPA 0.9.9 for decryption.
The used public key is a 4096 RSA key.

Did you use the latest version of php-gpg?

**Comment by tobestool** [comment]
Odd, I've just double checked and with code like yours above I get a block which GPA briefly flashes a decryption progress dialog then returns to the clipboard view with the block still there.

Mine is a 2048 bit RSA key, and I downloaded php-gpg from the project's front page this morning. Should I try a dev branch?

**Comment by DanielRuf** [comment]
If you create a file with the same content you will see that GPA successfully decrypts it (no text / content at all).

The clipboard view just shows something when there is something to decrypt. If there is nothing, it shows nothing. If there would be a problem with the decryption, it would show an error.

Please verify that it works with a file in the file view.

**Comment by tobestool** [comment]
Yes. That seems to successfully decrypt the block when put in a file. Thanks for that.

While GPA is giving no error, Enigmail does give a "Decryption Failed" error, so there is certainly something questionable going on. However it doesn't seem to be your code at fault. Thanks for the help clearing that up!

**Comment by jasonhinkle** [comment]
I just submitted it - https://packagist.org/packages/jasonhinkle/php-gpg
