### ISSUE TITLE
Hide version option 

### ISSUE THREAD

**Issue by RaedsLab** [jasonhinkle/php-gpg#16]
I think that `$gpg->encrypt($pub_key,$plain_text_string);` method should have a 3rd optional Boolean parameter `$show_version`. 

Hiding the client and the version in the encrypted text could prevent some future attacks on encrypted messages that target a specific version (if that version has been proven insecure).  

This was discussed in length in the openpgp.js project.

**Comment by DanielRuf** [comment]
Can you link to the openpgp.js discussion?

**Comment by RaedsLab** [comment]
@DanielRuf  https://mailman.stanford.edu/pipermail/liberationtech/2013-November/012243.html

**Comment by DanielRuf** [comment]
See my updated comment.

**Comment by RaedsLab** [comment]
I'm not an expert on the inner working of GnuPG but the decryption of a text without the comment  `Version: VerySimple PHP-GPG v1.4.7` works perfectly fine in the terminal.

**Comment by DanielRuf** [comment]
@jasonhinkle What do you think, should we add this to both branches?

**Comment by jasonhinkle** [comment]
Perhaps the 3rd parameter could be an optional string $version.  The default will be the same behavior as now.  If a $version is provided then use that instead. If an empty string is passed in, then no version info will show at all.

That way people who make their own clients can put in their version if they choose (like form mailers, etc) or just have no version info at all if they feel that is better for security purposes.

**Comment by DanielRuf** [comment]
Right, I will prepare a pull request with the suggested code tomorrow.

@RaedsLab I think this is flexible enough?

**Comment by RaedsLab** [comment]
@jasonhinkle @DanielRuf I thunk this works marvelously :+1:

**Comment by DanielRuf** [comment]
@RaedsLab please test it now with the latest master or dev branch. I've just committed the changes to the branches which allows custom version headers and omitting it completely.

**Comment by DanielRuf** [comment]
@RaedsLab please test it now with the latest master or dev branch. I've just committed the changes to the branches which allows custom version headers and omitting it completely.

**Comment by RaedsLab** [comment]
@DanielRuf sorry been busy with school, I'll test it tomorrow

**Comment by DanielRuf** [comment]
Okay.

**Comment by DanielRuf** [comment]
Any update? Because if it works we can update the version number and make a release.

**Comment by RaedsLab** [comment]
@DanielRuf : Sorry for the delay, tested it with both empty string, NULL, and custom value, all work perfectly !

**Comment by DanielRuf** [comment]
Great, thanks for the fedback.
