### ISSUE TITLE
stable build and version number (release)

### ISSUE THREAD

**Issue by DanielRuf** [jasonhinkle/php-gpg#17]
We have two version numbers, 1.1 here https://github.com/jasonhinkle/php-gpg/blob/master/libs/GPG.php#L20 and 1.4.7 here https://github.com/jasonhinkle/php-gpg/blob/master/libs/GPG.php#L33

How do they relate?

I think we can make a release (1.5.0, SemVer style for Packagist) here on GitHub and upate the version number.

**Comment by RaedsLab** [comment]
that would make the composer install a little easier if there were at least one stable version :+1:

**Comment by jasonhinkle** [comment]
line 20 i think was intended to refer to specifically that file GPG.php, whereas line 33 is the "library version"

I think really line 20 can probably just be dropped to avoid confusion. I don't think it's serving any purpose now that the library is in version control, we can all see the revision history without having to keep an arbitrary number in the file.

**Comment by DanielRuf** [comment]
Created the 1.5.0 release a few minutes ago.

@jasonhinkle possibly ou have to manually update the Packagist project to get the release there.

**Comment by jasonhinkle** [comment]
Cool nice work! I'll check out the best way to do it on packagist, perhaps creating a branch for the version?

**Comment by jasonhinkle** [comment]
looks like packagist is pulling from master so everything we merge into master will go up.  might be the most simple way to deal with it until the point comes where we have a breaking change.

**Comment by DanielRuf** [comment]
But you have to update it manually if the commit and pull request hooks are not setup on GitHub. Right, at the moment we have the labeled releae on Packagist and the master branch is uptodate =).

**Comment by jasonhinkle** [comment]
That's what I thought as well but when I went to look at it, it had already updated to 1.5.0.  I clicked the update button anyway, but i'm not sure it did anything?

**Comment by jasonhinkle** [comment]
actually i don't know what's going on! it seems to have picked up the 1.5.0 tag automatically though. is that good enough?

**Comment by DanielRuf** [comment]
Ok, it seems evrything is ok. I am not sure if they do automatic updates once per day or if it was triggered by the push and it was still cached for a few hours. Will take a eye on it when a new commit is pushed.

**Comment by jasonhinkle** [comment]
I just installed the service hook in github as well just in case, but it seems like it did pick up the tag without me doing that.  anyway, i think we should be fully covered now.

**Comment by DanielRuf** [comment]
Great :+1:
