### ISSUE TITLE
Generate MDC packets for better integrity protection

### ISSUE THREAD

**Issue by wyllys66** [jasonhinkle/php-gpg#18]
The Mailvelope plugin for Chrome and Firefox rejects messages without an MDC, which apparently is what 1.4.7 generates. I haven't tested with 1.5.0 yet. gpg just shows a warning when the MDC is missing. It's easy to test to see if the MDC is generated, just use "gpg --list-packets" on the encrypted message to see if it is generating an encrypted data packet with the mdc:

```
:encrypted data packet:
    length: unknown
    mdc_method: 2
```
The messages generate by php-pgp do not have the MDC method:
```
:encrypted data packet:
    length: 546
```

See: mailvelope/mailvelope#341

**Comment by DanielRuf** [comment]
https://tools.ietf.org/html/rfc4880#section-5.13

We have to add this packet in a future version.

**Comment by DanielRuf** [comment]
php-gpg 1.6.0 is now available and will add a MDC packet to encrypted messages.
