### ISSUE TITLE
Change confusing name

### ISSUE THREAD

**Issue by singpolyma** [jasonhinkle/php-gpg#21]
People are likely to confuse this library with the GnuPG project, since it takes its name from there.

**Comment by DanielRuf** [comment]
You are probably right. I think this wil need some time to find a good / proper name, communicate this change with other users and developers and update external ressources.

@jasonhinkle what do you think about this?

**Comment by jasonhinkle** [comment]
I don't understand the confusion - this project is exactly a port of gpg in PHP and is clear about it in the readme. What other name would make more sense?

I notice @singpolyma that you are working on a project called openpgp-php- I didn't know that it existed but would certainly be interested in knowing more about it.

**Comment by RaedsLab** [comment]
I found this project while searching in Github for "PHP GPG/GnuPG" I don't think that there is any confusion.

**Comment by singpolyma** [comment]
I it really a port of gpg? You are reading the gnupg C code and translating it for this project? I think instead it is an implementation of the OpenPGP format, which GnuPG is also an implementation of.  It's like building a new email client in php and calling it "php-thunderbird"

**Comment by jasonhinkle** [comment]
That is pretty much what this started as - converting GPG C code into PHP.

I can't help but feel Steve that you have some personal motives about this name - I have no idea why, we're all just trying to make encryption available to PHP developers.

**Comment by singpolyma** [comment]
@jasonhinkle No personal motive.  Just seemed confusing is all :)

**Comment by jasonhinkle** [comment]
Well there's certainly no reward for any of us making PHP tools for encryption- I'd be happy to work together. @DanielRuf is really doing all of the work recently, I'm pretty much just the maintainer in name only.

**Comment by jasonhinkle** [comment]
Btw guys I am quite seriously ill, if anybody wanted to fork this project I'd be happy to point to it regardless of the name. I'm unsure how much longer I'll be able to do even the small amount of work I do here.
