### ISSUE TITLE
Error when run tests

### ISSUE THREAD

**Issue by danelsan** [jasonhinkle/php-gpg#30]
I run into folder tests:

sh runtests.sh

but I receive this errors (I work with linux ):

PHP Warning:  require_once(PHPUnit/Framework/TestCase.php): failed to open stream: No such file or directory in /home/daniele/development/php/php-gpg/php-gpg/tests/gpg/EncryptTest.php on line 11
PHP Fatal error:  require_once(): Failed opening required 'PHPUnit/Framework/TestCase.php' (include_path='/home/daniele/development/php/php-gpg/php-gpg/libs:.:/usr/share/php:/usr/share/pear') in /home/daniele/development/php/php-gpg/php-gpg/tests/gpg/EncryptTest.php on line 11

**Comment by DanielRuf** [comment]
This could be because PHPUnit should reside in the same folder as the library and added as dependency to the Composer file.

Currently there are no test depencencies defined.

https://github.com/jasonhinkle/php-gpg/blob/master/composer.json
