### ISSUE TITLE
Error run tests phpunit

### ISSUE THREAD

**Issue by danelsan** [jasonhinkle/php-gpg#31]
I now run the test but i give these errors:

There were 2 failures:

1) KeyTest::test_VerifyGnuPGKey
OpenPGP Incorrect Key ID
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'47009B66424E9476'
+'04343C988F215A2E'

/home/daniele/development/php/php-gpg/php-gpg/tests/gpg/KeyTest.php:1420

2) KeyTest::test_VerifyOpenPGPKey2
OpenPGP Incorrect Key ID
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'C87538697986219A'
+'38B09C3E598ED36F'

/home/daniele/development/php/php-gpg/php-gpg/tests/gpg/KeyTest.php:1454

FAILURES!
Tests: 5, Assertions: 9, Errors: 1, Failures: 2.

**Comment by DanielRuf** [comment]
Not sure, maybe the key IDs are just wrong and the actual key IDs of the used keys are different? Personally I do not have much time to collaborate anymore and moved projects to https://github.com/singpolyma/openpgp-php

**Comment by danelsan** [comment]
ok, thanks
