### ISSUE TITLE
Problems with gnupg-generated keypair.

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [jasonhinkle/php-gpg#7]
Hello. I have encountered a problem. First, I created a keypair using gnupg and passphrase `123`:
```
gpg --batch --gen-key <(cat <<< $'Key-Type:RSA\nKey-Length:4096\nSubkey-Type:RSA\nSubkey-Length:4096\nExpire-Date:0\nName-Real:TestKeyPair\nPassphrase:123\n%pubring secring.pub\n%secring secring.sec\n%commit\n%echo done');gpg --armor --no-default-keyring --keyring ./secring.pub --output pubkey.txt --export TestKeyPair
```
Second - I tested if those keys are valid and I can encrypt and decrypt messages via the gnupg:
```
echo -n TESTMESSAGETEXT>msg.txt
```
```
gpg --always-trust --armor --encrypt --output msg.gnugp-encrypted.txt --no-default-keyring --keyring ./secring.pub --recipient TestKeyPair msg.txt
```
```
gpg --output msg.gnugp-encrypted.decrypt-result.txt --no-default-keyring --keyring ./secring.pub --secret-keyring ./secring.sec --decrypt msg.gnugp-encrypted.txt
```
```
diff --report-identical-files msg.txt msg.gnugp-encrypted.decrypt-result.txt
```
Then I encrypted a message with php-gpg:
```
php -r "require_once 'libs/GPG.php';\$gpg = new GPG();file_put_contents('msg.phpgpg-encrypted.txt',\$gpg->encrypt(new GPG_Public_Key(file_get_contents('pubkey.txt')),file_get_contents('msg.txt')));"
```
And after that I can't decrypt it with gnupg the same way I decrypted the gnupg-encrypted message, it gives me an error:
```
$ gpg --output msg.phpgpg-encrypted.decrypt-result.txt --no-default-keyring --keyring ./secring.pub --secret-keyring ./secring.sec --decrypt msg.phpgpg-encrypted.txt

You need a passphrase to unlock the secret key for
user: "TestKeyPair"
4096-bit RSA key, ID 15C6642A, created 2015-07-05

gpg: encrypted with 4096-bit RSA key, ID 15C6642A, created 2015-07-05
      "TestKeyPair"
gpg: public key decryption failed: wrong secret key used
gpg: decryption failed: secret key not available
```
What am I doing wrong and is it possible to solve this problem?
As long as github does not allows to attach files, I post an archive with all these generated files as a link: http://space1000.ru/wp-content/uploads/2015/07/bugreport.7z

**Comment by yetanotherusernamebecausegithubisbugged** [comment]
I'm also getting an error while trying to encrypt message with 2048-length key:
```
$ php -r "require_once 'libs/GPG.php';\$gpg = new GPG();file_put_contents('msg.phpgpg-encrypted.txt',\$gpg->encrypt(new GPG_Public_Key(file_get_contents('pubkey.txt')),file_get_contents('msg.txt')));"
PHP Notice:  Undefined offset: 1452 in /home/me/tst/gnupg/test2/libs/GPG/Public_Key.php on line 98
PHP Notice:  Undefined offset: 1453 in /home/me/tst/gnupg/test2/libs/GPG/Public_Key.php on line 98
PHP Notice:  Undefined offset: -1084029522 in /home/me/tst/gnupg/test2/libs/GPG/Public_Key.php on line 81
```
http://space1000.ru/wp-content/uploads/2015/07/test2.7z

**Comment by DanielRuf** [comment]
This seems to be a problem with the GnuPG version.

I use GnuPG v2 and it works. But with your GnuPG v1.4.11 public key it does not work.

Did you already test with a gpg2 key?

https://www.gnupg.org/download/index.html
```
GnuPG classic (1.4) is the old, single binary version which may be build even on ancient Unix platforms. It has no dependencies on the above listed libraries or the Pinnetry. However, it lacks many modern features.
```

```
GnuPG stable (2.0) is the modularized version of GnuPG supporting OpenPGP, S/MIME, and Secure Shell.
```
It seems GnuPG 1 is not supported at the moment.

**Comment by jasonhinkle** [comment]
Hey @DanielRuf thank you so much for putting the work in.  Would you have any interest in being a committer for the project? I haven't had the time to maintain this as I should. I think it's a great library for the PHP community.

**Comment by DanielRuf** [comment]
@jasonhinkle It is a great library for the PHP community for sure. I don't know if I have the time for it but I will commit as much as I can and try to fix these issues.

**Comment by jasonhinkle** [comment]
@DanielRuf That is more than I've been able to do. I just added you. Thanks again!

**Comment by DanielRuf** [comment]
Tested it with https://github.com/jasonhinkle/php-gpg/tree/7a0e41e7eee5739e99ba6147fbf78ddc4329a62a

Imported they keys using GPA.
Encrypted the file with php-gpg and then decrypted it successfully using GPA.

I think the latest commits also fixed this issue.

Can you verify this @jasonhinkle?

The second issue still exists with gpg classic keys. I could not verify it with a gpg stable (2.0) key as these use the new header format.

The isse is in this line where the 24 left bit shift produces an integer overflow (on 32 bit systems):
https://github.com/jasonhinkle/php-gpg/blob/7a0e41e7eee5739e99ba6147fbf78ddc4329a62a/libs/GPG/Public_Key.php#L98

**Comment by jasonhinkle** [comment]
my tests are showing all green.  i'll close the issue - if anybody still has problems, please re-open. thanks Daniel!
